module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'node',
  roots: ['<rootDir>/src'],
  testMatch: ['**/__tests__/**/*.+(ts|js)', '**/?(*.)+(spec|test).+(ts|js)'],
  setupFiles: ['dotenv/config'],
  setupFilesAfterEnv: ['<rootDir>/src/tests/setup.ts'],
  globalSetup: '<rootDir>/jest.global-setup.js',
  collectCoverage: true,
  collectCoverageFrom: [
    'src/**/*.{ts,js}',
    '!src/index.ts',
    '!src/**/*.d.ts',
    '!src/infrastructure/**',
    '!src/adapters/**',
  ],
  coverageReporters: ['text', 'lcov', 'cobertura'],
  coverageDirectory: '<rootDir>/coverage',
  coveragePathIgnorePatterns: [
    '/node_modules/',
    '<rootDir>/src/lib/logger.ts',
    '<rootDir>/src/lib/openai.ts',
    '<rootDir>/src/lib/paypal.ts',
    '<rootDir>/src/lib/mailer.ts',
    '<rootDir>/src/lib/prisma.ts',
    '<rootDir>/src/middleware/requestId.ts',
    '<rootDir>/src/middleware/rateLimit.ts',
  ],
  coverageThreshold: {
    global: {
      branches: 80,
      functions: 80,
      lines: 80,
      statements: 80,
    },
  },
};